mindmap
    root((Valles Lab))
        Microbiome data analysis in the GBA
            Microbial biotransformation of neuroactive compounds
                Performing a study
                    Study design
                        Statistical power calculation
                    **Sequencing method**
                        16S
                            Pros
                                Useful when there's too much host DNA
                                    Biopsies
                            Cons
                                Up to genus level
                                PCR bias
                                16S primers are not universal
                        Shotgun
                            QC
                                Host reads
                                Low quality reads
                                Adapters
                            Profiling
                                **Reference-based**
                                    More sensitive
                                    Misses taxa/functions not present in DBs
                                    Tools
                                        MetaPhlAn
                                            Mireia contributes
                                        mOTUs
                                        Kraken + Bracken
                                **Reference-free**
                                    Less sensitive
                                    Computationally intensive
                                    Captures everything
                                    Contigs
                                            Binning
                                                MAGs
                            Dealing with compositionality
                                qPCR
                                    Primers are not universal
                                QMP
                                    Flow cytometry
        Transmission of the microbiome neuroactive potential